---
# This role will install restify.
# In deploy mode it will deploy an restify server.
# In clean mode it will remove the restify server

- include: deploy.yml
  when: mode == "deploy"

- include: clean.yml
  when: mode == "clean"

